### ISSUE TITLE
Make this a one-click operation!

### ISSUE THREAD

**Issue by Thor--** [NIVeriStandAdd-Ons/ScriptedModelTemplate#4]
Would be great if the path was auto-populated, and it just went ahead and built the release version.

When it's done, it should pop up a "Success" dialog along with the filepath where the resulting project ended up.

**Comment by Electric-Spark** [comment]
Eh, I think it'd be nice to auto-populate the path and get rid of the buttons (always build always release) but I think it should still let you change the path to the VI if you want before building. That way you could choose the tool from the splashscreen or a different VI.

**Comment by smithed** [comment]
done in both
